blank_issues_enabled: false
contact_links:
  - name: 💬Allure Report Community
    url: https://github.com/orgs/allure-framework/discussions
    about: Please ask and answer questions here.
  - name: Allure TestOps Support
    url: https://help.qameta.io/support/home
    about: Please report Allure TestOps issues here.
